# Generated by Django 3.1 on 2021-02-06 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('no_challenges_solved', models.IntegerField()),
                ('votes', models.IntegerField(default=0)),
                ('python_rating', models.IntegerField(default=1)),
                ('dsa_rating', models.IntegerField(default=1)),
                ('cplus_rating', models.IntegerField(default=1)),
                ('java_rating', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='None', max_length=50, unique=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='main.candidate')),
            ],
        ),
    ]
